apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      imagePullSecrets:
      - name: my-secret
      containers:
      - name: customer
        image: customer:1.0
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always