apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: Y3VzdG9tZXI=
  password: aXRzYXNlY3JldA==
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  uri: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvcG9zdGdyZXM=
