apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
type: Opaque
data:
  username: Y3VzdG9tZXI=
  password: aXRzYXNlY3JldA==
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  database_uri: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvcG9zdGdyZXM=
