apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  type: LoadBalancer
  selector:
    app: customer
  ports:
    - name: primary
      protocol: TCP
      port: 80
      targetPort: 8080
