apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  # type: LoadBalancer
  selector:
    app: customer
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
    - name: primary
      protocol: TCP
      port: 8080
      targetPort: 8080
